apiVersion: management.cattle.io/v3
kind: RoleTemplate
displayName: SUSE Observability Instance Troubleshooter
description: Troubleshoot with SUSE Observability
builtin: false
hidden: false
external: false
context: project
metadata:
  name: suse-observability-instance-troubleshooter
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - instance.observability.cattle.io
  resources:
  - views
  - monitors
  - notifications
  - stackpackconfigurations
  - dashboards
  verbs:
  - create
  - update
  - get
  - delete
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - agents
    - apitokens
    - metrics
    - metricbindings
    - settings
    - stackpacks
    - systemnotifications
    - topology
    - traces
  verbs:
    - get
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - visualizationsettings
  verbs:
    - update
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - componentactions
    - monitors
  verbs:
    - execute
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - favoriteviews
    - favoritedashboards
  verbs:
    - delete
    - create
