apiVersion: management.cattle.io/v3
kind: RoleTemplate
displayName: SUSE Observability Instance Guest
description: Read-only access to all data the SUSE Observability instance
builtin: true
hidden: false
external: false
context: project
metadata:
  name: suse-observability-instance-guest
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
rules:
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - metrics
    - topology
    - traces
  verbs:
    - get
