apiVersion: management.cattle.io/v3
kind: RoleTemplate
displayName: SUSE Observability Instance Poweruser
description: Poweruser the SUSE Observability instance
builtin: true
hidden: false
external: false
context: project
metadata:
  name: suse-observability-instance-poweruser
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
rules:
- apiGroups:
  - instance.observability.cattle.io
  resources:
  - views
  - metricbindings
  - monitors
  - notifications
  - settings
  - stackpackconfigurations
  verbs:
  - create
  - update
  - get
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - dashboards
  verbs:
    - create
    - update
    - get
    - delete
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - agents
    - apitokens
    - metrics
    - metricbindings
    - syncdata
    - systemnotifications
    - topology
    - topicmessages
    - traces
    - stackpacks
  verbs:
    - get
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - syncdata
    - visualizationsettings
  verbs:
    - update
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - componentactions
    - monitors
  verbs:
    - execute
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - favoriteviews
    - syncdata
    - favoritedashboards
  verbs:
    - delete
- apiGroups:
    - instance.observability.cattle.io
  resources:
    - favoriteviews
    - favoritedashboards
  verbs:
    - create
