apiVersion: management.cattle.io/v3
kind: RoleTemplate
displayName: SUSE Observability Basic Access
description: Basic Access to SUSE Observability
builtin: true
hidden: false
external: false
context: project
metadata:
  name: suse-observability-basic-access
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - instance.observability.cattle.io
    resources:
      - views
      - apitokens
      - systemnotifications
      - settings
      - stackpacks
      - metricbindings
    verbs:
      - get
  - apiGroups:
      - instance.observability.cattle.io
    resources:
      - visualizationsettings
    verbs:
      - update
  - apiGroups:
      - instance.observability.cattle.io
    resources:
      - componentactions
    verbs:
      - execute
  - apiGroups:
      - instance.observability.cattle.io
    resources:
      - favoriteviews
    verbs:
      - update
      - delete
      - create
