name: Generate and publish Helm charts

inputs:
  tagged_release:
    description: The tag of the release
    required: true
  target_branch:
    description: The branch to push the charts to
    required: true
  GITHUB_TOKEN:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Build and Publish Packages
      shell: bash
      run: |
        yarn publish-pkgs \
          -s "${{ github.repository }}" \
          -b "${{ inputs.target_branch }}" \
          -t "${{ inputs.tagged_release }}"

    # Move build artifacts to a temporary directory due to checkout reset
    - name: Move Build Artifacts to Temporary Directory
      id: artifacts
      shell: bash
      run: |
        TEMP_DIR=$(mktemp -d "${RUNNER_TEMP}/build_artifacts_XXXXXX")
        mv tmp/* "$TEMP_DIR"
        echo "dir=$TEMP_DIR" >> $GITHUB_OUTPUT

    - name: Set Up Helm CLI
      uses: azure/setup-helm@v3
      with:
        version: v3.8.0

    - name: Checkout Target Branch
      uses: actions/checkout@v4
      with:
        ref: "${{ inputs.target_branch }}"

    - name: Restore Build Artifacts to Working Directory
      shell: bash
      run: |
        rsync -av --ignore-existing "${{ steps.artifacts.outputs.dir }}/" .

    - name: Verify Untracked Files
      shell: bash
      run: git status

    - name: Commit and Push Changes
      shell: bash
      run: |
        git add ./{assets,charts,extensions,index.yaml}
        git commit -m "CI: Publish Helm charts for ${{ inputs.tagged_release }}"
        git push

    - name: Release Helm Charts
      uses: helm/chart-releaser-action@v1.4.1
      with:
        charts_dir: ./charts/*
      env:
        CR_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
        CR_SKIP_EXISTING: true
