export const OBSERVABILITY_PRODUCT_NAME = "observability";
export const BLANK_CLUSTER = "_";

export const OBSERVABILITY_DASHBOARD = "observability.rancher.io.dashboard";

export const HEALTH_STATE_TYPES = {
  UNKNOWN: "UNKNOWN",
  CLEAR: "CLEAR",
  DEVIATING: "DEVIATING",
  CRITICAL: "CRITICAL",
  CONNECTION_ERROR: "CONNECTION_ERROR",
  UNCONFIGURED: "UNCONFIGURED",
  UNOBSERVED: "UNOBSERVED",
};
