name: Read changeset status

outputs:
  release:
    description: |
      The release version of the changeset:
      {
        name: string,
        type: "path" | "minor" | "major",
        oldVersion: string
        newVersion: string
      }
    value: ${{ steps.status.outputs.release }}

runs:
  using: composite
  steps:
    - name: Print remotes
      shell: bash
      run: git remote -v

    - name: Read Changeset Status
      shell: bash
      id: status
      run: |
        OUTPUT=$(mktemp ${{runner.temp}}/changeset-output.XXXXXX.json)

        if [ ! -f "$OUTPUT" ]; then
          echo "Failed to create temp file at: $OUTPUT"
          exit 1
        fi
        echo "Temporary file created at: $OUTPUT"

        BASE_BRANCH=$(jq -r '.baseBranch' .changeset/config.json)

        # the `changeset status` command uses path.join so the path should be relative
        yarn changeset status --since origin/$BASE_BRANCH --output $(realpath --relative-to . $OUTPUT)

        if [ ! -s "$OUTPUT" ]; then
          echo "Error: Temporary file is empty after running 'yarn changeset status'"
          exit 1
        fi

        RELEASE=$(jq -r '.releases[0]' "$OUTPUT")

        echo "release=$RELEASE" >> $GITHUB_OUTPUT
        echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
