name: Read changeset status

outputs:
  base_branch:
    description: The value of 'baseBranch' field from .changeset/config.json
    value: ${{ steps.status.outputs.base_branch }}

  release:
    description: |
      The release version of the changeset if any:
      {
        name: string,
        type: "patch" | "minor" | "major",
        oldVersion: string,
        newVersion: string
      }
    value: ${{ steps.status.outputs.release }}

runs:
  using: composite
  steps:
    - name: Read Changeset Status
      shell: bash
      id: status
      run: |
        OUTPUT=$(mktemp "${{runner.temp}}/changeset-output.XXXXXX.json")

        if [ ! -f "$OUTPUT" ]; then
          echo "🚨 Error: Failed to create temp file at: $OUTPUT"
          exit 1
        fi
        echo "✅ Temporary file created at: $OUTPUT"

        # Read the base branch from the changeset configuration
        BASE_BRANCH=$(jq -r '.baseBranch' .changeset/config.json)

        # Run the changeset status command with relative path output
        yarn changeset status --since "origin/$BASE_BRANCH" --output $(realpath --relative-to . "$OUTPUT")

        if [ ! -s "$OUTPUT" ]; then
          echo "🚨 Error: Temporary file is empty after running 'yarn changeset status'"
          exit 1
        fi

        RELEASE=$(jq -c '.releases[0] // empty' "$OUTPUT")

        # PRINT THE RELEASE CONTENT
        echo "RELEASE: $RELEASE"

        echo "release=" >> $GITHUB_OUTPUT
        echo "base_branch=$BASE_BRANCH" >> $GITHUB_OUTPUT
