apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suse-observability-rancher
rules:
  - apiGroups:
      - observability.rancher.io
    resources:
      - configurations
    verbs:
      - get
      - list
