apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: suse-observability-extension-user
  namespace: suse-observability-extension
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: suse-observability-extension-user
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
